// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quanlythuvien.Models;

#nullable disable

namespace Quanlythuvien.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250625055845_qltv")]
    partial class qltv
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Quanlythuvien.Models.Login.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            id = 1,
                            password = "2004",
                            username = "Admin1"
                        },
                        new
                        {
                            id = 2,
                            password = "2004",
                            username = "Admin2"
                        },
                        new
                        {
                            id = 3,
                            password = "2004",
                            username = "Admin3"
                        },
                        new
                        {
                            id = 4,
                            password = "2004",
                            username = "Admin4"
                        },
                        new
                        {
                            id = 5,
                            password = "2004",
                            username = "Admin5"
                        },
                        new
                        {
                            id = 6,
                            password = "2004",
                            username = "Admin6"
                        },
                        new
                        {
                            id = 7,
                            password = "2004",
                            username = "Admin7"
                        },
                        new
                        {
                            id = 8,
                            password = "2004",
                            username = "Admin8"
                        },
                        new
                        {
                            id = 9,
                            password = "2004",
                            username = "Admin9"
                        },
                        new
                        {
                            id = 10,
                            password = "2004",
                            username = "Admin110"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
