// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quanlythuvien.Models;

#nullable disable

namespace Quanlythuvien.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Quanlythuvien.Models.Admins.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "2004",
                            Username = "Admin1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "2004",
                            Username = "Admin2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "2004",
                            Username = "Admin3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "2004",
                            Username = "Admin4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "2004",
                            Username = "Admin5"
                        },
                        new
                        {
                            Id = 6,
                            Password = "2004",
                            Username = "Admin6"
                        },
                        new
                        {
                            Id = 7,
                            Password = "2004",
                            Username = "Admin7"
                        });
                });

            modelBuilder.Entity("Quanlythuvien.Models.DocGia", b =>
                {
                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSachMuonToiDa")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDangKy")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDocGia");

                    b.ToTable("DocGias");

                    b.HasData(
                        new
                        {
                            MaDocGia = "DG001",
                            DiaChi = "12 Tràng Tiền, Hà Nội",
                            Email = "nguyenvana@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Nguyễn Văn An",
                            NgayDangKy = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            SoSachMuonToiDa = 5,
                            TienDangKy = 50000m
                        },
                        new
                        {
                            MaDocGia = "DG002",
                            DiaChi = "45 Lê Lợi, TP.HCM",
                            Email = "tranthib@example.com",
                            GioiTinh = "Nữ",
                            HoTen = "Trần Thị Bình",
                            NgayDangKy = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1998, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0934567890",
                            SoSachMuonToiDa = 6,
                            TienDangKy = 60000m
                        },
                        new
                        {
                            MaDocGia = "DG003",
                            DiaChi = "99 Phạm Văn Đồng, TP.HCM",
                            Email = "lehoangc@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Lê Hoàng Cường",
                            NgayDangKy = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2002, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0971122334",
                            SoSachMuonToiDa = 4,
                            TienDangKy = 55000m
                        },
                        new
                        {
                            MaDocGia = "DG004",
                            DiaChi = "18 Điện Biên Phủ, Hà Nội",
                            Email = "phaminhd@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Phạm Minh Duy",
                            NgayDangKy = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1988, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0908123456",
                            SoSachMuonToiDa = 5,
                            TienDangKy = 100000m
                        },
                        new
                        {
                            MaDocGia = "DG005",
                            DiaChi = "6 Nguyễn Trãi, Hà Nội",
                            Email = "dangthuye@example.com",
                            GioiTinh = "Nữ",
                            HoTen = "Đặng Thùy Huyền",
                            NgayDangKy = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2000, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0369988776",
                            SoSachMuonToiDa = 5,
                            TienDangKy = 45000m
                        },
                        new
                        {
                            MaDocGia = "DG006",
                            DiaChi = "150 Hai Bà Trưng, TP.HCM",
                            Email = "voquocf@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Võ Quốc Toàn",
                            NgayDangKy = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1993, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0924455667",
                            SoSachMuonToiDa = 7,
                            TienDangKy = 70000m
                        },
                        new
                        {
                            MaDocGia = "DG007",
                            DiaChi = "210 Nguyễn Huệ, Huế",
                            Email = "ngoducg@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Ngô Đức Duy",
                            NgayDangKy = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1979, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0919988775",
                            SoSachMuonToiDa = 3,
                            TienDangKy = 120000m
                        },
                        new
                        {
                            MaDocGia = "DG008",
                            DiaChi = "34 Trần Hưng Đạo, Nam Định",
                            Email = "buithih@example.com",
                            GioiTinh = "Nữ",
                            HoTen = "Bùi Thị Hằng",
                            NgayDangKy = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(2005, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0988112233",
                            SoSachMuonToiDa = 5,
                            TienDangKy = 40000m
                        },
                        new
                        {
                            MaDocGia = "DG009",
                            DiaChi = "8 Lý Thường Kiệt, Đà Nẵng",
                            Email = "trinhgiai@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Trịnh Gia Bảo",
                            NgayDangKy = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1991, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0955667788",
                            SoSachMuonToiDa = 6,
                            TienDangKy = 80000m
                        },
                        new
                        {
                            MaDocGia = "DG010",
                            DiaChi = "35 Nguyễn Văn Cừ, Nha Trang",
                            Email = "hoangmyk@example.com",
                            GioiTinh = "Nữ",
                            HoTen = "Hoàng Mỹ Khánh",
                            NgayDangKy = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgaySinh = new DateTime(1985, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0965123456",
                            SoSachMuonToiDa = 5,
                            TienDangKy = 65000m
                        });
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuMuons.ChiTietPhieuMuon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DaTra")
                        .HasColumnType("bit");

                    b.Property<string>("MaPhieuMuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaPhieuMuon");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuMuons.PhieuMuon", b =>
                {
                    b.Property<string>("MaPhieuMuon")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MaDocGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayPhaiTra")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("MaDocGia");

                    b.ToTable("PhieuMuons");

                    b.HasData(
                        new
                        {
                            MaPhieuMuon = "PM1",
                            MaDocGia = "DG001",
                            NgayMuon = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieuMuon = "PM2",
                            MaDocGia = "DG001",
                            NgayMuon = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuTras.ChiTietPhieuTra", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhieuTra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhieuTraMaPhieuTra")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("MaSach");

                    b.HasIndex("PhieuTraMaPhieuTra");

                    b.ToTable("ChiTietPhieuTras");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuTras.PhieuTra", b =>
                {
                    b.Property<string>("MaPhieuTra")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MaPhieuMuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuTra");

                    b.HasIndex("MaPhieuMuon");

                    b.ToTable("PhieuTras");

                    b.HasData(
                        new
                        {
                            MaPhieuTra = "PT001",
                            MaPhieuMuon = "PM1",
                            NgayTra = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TienPhat = 0m
                        },
                        new
                        {
                            MaPhieuTra = "PT002",
                            MaPhieuMuon = "PM2",
                            NgayTra = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TienPhat = 500m
                        });
                });

            modelBuilder.Entity("Quanlythuvien.Models.Sachs.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NamPhatHanh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaSach");

                    b.ToTable("Sachs");

                    b.HasData(
                        new
                        {
                            MaSach = "S001",
                            DonGia = 90000m,
                            NamPhatHanh = 2007,
                            NgayNhap = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Kim Đồng",
                            SoLuong = 5,
                            TenSach = "Dế Mèn Phiêu Lưu Ký",
                            TenTacGia = "Tô Hoài",
                            TheLoai = "Thiếu nhi"
                        },
                        new
                        {
                            MaSach = "S002",
                            DonGia = 75000m,
                            NamPhatHanh = 1950,
                            NgayNhap = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 4,
                            TenSach = "Lão Hạc",
                            TenTacGia = "Nam Cao",
                            TheLoai = "Văn học"
                        },
                        new
                        {
                            MaSach = "S003",
                            DonGia = 150000m,
                            NamPhatHanh = 2011,
                            NgayNhap = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tri Thức",
                            SoLuong = 6,
                            TenSach = "Sapiens",
                            TenTacGia = "Yuval N. Harari",
                            TheLoai = "Khoa học"
                        },
                        new
                        {
                            MaSach = "S004",
                            DonGia = 95000m,
                            NamPhatHanh = 1981,
                            NgayNhap = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 3,
                            TenSach = "Totto‑Chan Bên Cửa Sổ",
                            TenTacGia = "Tetsuko Kuroyanagi",
                            TheLoai = "Thiếu nhi"
                        },
                        new
                        {
                            MaSach = "S005",
                            DonGia = 120000m,
                            NamPhatHanh = 1936,
                            NgayNhap = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tổng Hợp",
                            SoLuong = 7,
                            TenSach = "Đắc Nhân Tâm",
                            TenTacGia = "Dale Carnegie",
                            TheLoai = "Kỹ năng"
                        },
                        new
                        {
                            MaSach = "S006",
                            DonGia = 110000m,
                            NamPhatHanh = 1988,
                            NgayNhap = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 4,
                            TenSach = "Nhà Giả Kim",
                            TenTacGia = "Paulo Coelho",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S007",
                            DonGia = 135000m,
                            NamPhatHanh = 2011,
                            NgayNhap = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tri Thức",
                            SoLuong = 6,
                            TenSach = "Tư Duy Nhanh Và Chậm",
                            TenTacGia = "Daniel Kahneman",
                            TheLoai = "Khoa học"
                        },
                        new
                        {
                            MaSach = "S008",
                            DonGia = 85000m,
                            NamPhatHanh = 1990,
                            NgayNhap = new DateTime(2025, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 5,
                            TenSach = "Mắt Biếc",
                            TenTacGia = "Nguyễn Nhật Ánh",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S009",
                            DonGia = 99000m,
                            NamPhatHanh = 2004,
                            NgayNhap = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Lao Động",
                            SoLuong = 4,
                            TenSach = "Bí Mật Của Nước",
                            TenTacGia = "Masaru Emoto",
                            TheLoai = "Khoa học"
                        },
                        new
                        {
                            MaSach = "S010",
                            DonGia = 125000m,
                            NamPhatHanh = 1946,
                            NgayNhap = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Lao Động",
                            SoLuong = 4,
                            TenSach = "Đi Tìm Lẽ Sống",
                            TenTacGia = "Viktor E. Frankl",
                            TheLoai = "Tâm lý"
                        },
                        new
                        {
                            MaSach = "S011",
                            DonGia = 118000m,
                            NamPhatHanh = 1989,
                            NgayNhap = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tổng Hợp",
                            SoLuong = 6,
                            TenSach = "7 Thói Quen Hiệu Quả",
                            TenTacGia = "Stephen R. Covey",
                            TheLoai = "Kỹ năng"
                        },
                        new
                        {
                            MaSach = "S012",
                            DonGia = 105000m,
                            NamPhatHanh = 2016,
                            NgayNhap = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tri Thức",
                            SoLuong = 5,
                            TenSach = "Cuộc Cách Mạng 4.0",
                            TenTacGia = "Klaus Schwab",
                            TheLoai = "Kinh tế"
                        },
                        new
                        {
                            MaSach = "S013",
                            DonGia = 89000m,
                            NamPhatHanh = 2010,
                            NgayNhap = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 3,
                            TenSach = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
                            TenTacGia = "Nguyễn Nhật Ánh",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S014",
                            DonGia = 95000m,
                            NamPhatHanh = 2014,
                            NgayNhap = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Lao Động",
                            SoLuong = 5,
                            TenSach = "Khéo Ăn Nói...",
                            TenTacGia = "Trác Nhã",
                            TheLoai = "Kỹ năng"
                        },
                        new
                        {
                            MaSach = "S015",
                            DonGia = 99000m,
                            NamPhatHanh = 1813,
                            NgayNhap = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 4,
                            TenSach = "Kiêu Hãnh & Định Kiến",
                            TenTacGia = "Jane Austen",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S016",
                            DonGia = 140000m,
                            NamPhatHanh = 1892,
                            NgayNhap = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 7,
                            TenSach = "Sherlock Holmes Tuyển Tập",
                            TenTacGia = "Arthur C. Doyle",
                            TheLoai = "Trinh thám"
                        },
                        new
                        {
                            MaSach = "S017",
                            DonGia = 135000m,
                            NamPhatHanh = 1997,
                            NgayNhap = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 6,
                            TenSach = "Harry Potter 1: Hòn Đá Phù Thủy",
                            TenTacGia = "J.K. Rowling",
                            TheLoai = "Fantasy"
                        },
                        new
                        {
                            MaSach = "S018",
                            DonGia = 108000m,
                            NamPhatHanh = 2016,
                            NgayNhap = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tri Thức",
                            SoLuong = 3,
                            TenSach = "Khi Hơi Thở Hóa Thinh Không",
                            TenTacGia = "Paul Kalanithi",
                            TheLoai = "Tự truyện"
                        },
                        new
                        {
                            MaSach = "S019",
                            DonGia = 78000m,
                            NamPhatHanh = 2015,
                            NgayNhap = new DateTime(2025, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 4,
                            TenSach = "Cà Phê Cùng Tony",
                            TenTacGia = "Tony Buổi Sáng",
                            TheLoai = "Kỹ năng"
                        },
                        new
                        {
                            MaSach = "S020",
                            DonGia = 145000m,
                            NamPhatHanh = 1943,
                            NgayNhap = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 3,
                            TenSach = "Suối Nguồn",
                            TenTacGia = "Ayn Rand",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S021",
                            DonGia = 112000m,
                            NamPhatHanh = 2004,
                            NgayNhap = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tổng Hợp",
                            SoLuong = 5,
                            TenSach = "Kỷ Luật Tự Giác",
                            TenTacGia = "Stephen R. Covey",
                            TheLoai = "Kỹ năng"
                        },
                        new
                        {
                            MaSach = "S022",
                            DonGia = 130000m,
                            NamPhatHanh = 1997,
                            NgayNhap = new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Trẻ",
                            SoLuong = 6,
                            TenSach = "Cha Giàu Cha Nghèo",
                            TenTacGia = "R. T. Kiyosaki",
                            TheLoai = "Kinh tế"
                        },
                        new
                        {
                            MaSach = "S023",
                            DonGia = 88000m,
                            NamPhatHanh = 1968,
                            NgayNhap = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Lao Động",
                            SoLuong = 4,
                            TenSach = "Người Bán Hàng Vĩ Đại",
                            TenTacGia = "Og Mandino",
                            TheLoai = "Kỹ năng"
                        },
                        new
                        {
                            MaSach = "S024",
                            DonGia = 118000m,
                            NamPhatHanh = 1969,
                            NgayNhap = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 7,
                            TenSach = "Bố Già",
                            TenTacGia = "Mario Puzo",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S025",
                            DonGia = 128000m,
                            NamPhatHanh = 1967,
                            NgayNhap = new DateTime(2025, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 5,
                            TenSach = "Trăm Năm Cô Đơn",
                            TenTacGia = "G. G. Márquez",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S026",
                            DonGia = 92000m,
                            NamPhatHanh = 1952,
                            NgayNhap = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 3,
                            TenSach = "Ông Già Và Biển Cả",
                            TenTacGia = "Ernest Hemingway",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S027",
                            DonGia = 104000m,
                            NamPhatHanh = 1949,
                            NgayNhap = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 4,
                            TenSach = "Hoa Nhẫn Thạch",
                            TenTacGia = "Yasunari Kawabata",
                            TheLoai = "Tiểu thuyết"
                        },
                        new
                        {
                            MaSach = "S028",
                            DonGia = 132000m,
                            NamPhatHanh = 2011,
                            NgayNhap = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Tri Thức",
                            SoLuong = 5,
                            TenSach = "The Lean Startup",
                            TenTacGia = "Eric Ries",
                            TheLoai = "Kinh tế"
                        },
                        new
                        {
                            MaSach = "S029",
                            DonGia = 119000m,
                            NamPhatHanh = 2014,
                            NgayNhap = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Lao Động",
                            SoLuong = 4,
                            TenSach = "Thiên Tài Bên Trái...",
                            TenTacGia = "Eric B. T. Lin",
                            TheLoai = "Khoa học"
                        },
                        new
                        {
                            MaSach = "S030",
                            DonGia = 103000m,
                            NamPhatHanh = 1947,
                            NgayNhap = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NhaXuatBan = "NXB Văn Học",
                            SoLuong = 6,
                            TenSach = "Nhật Ký Anne Frank",
                            TenTacGia = "Anne Frank",
                            TheLoai = "Tự truyện"
                        });
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuMuons.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("Quanlythuvien.Models.PhieuMuons.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quanlythuvien.Models.Sachs.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuMuons.PhieuMuon", b =>
                {
                    b.HasOne("Quanlythuvien.Models.DocGia", "DocGia")
                        .WithMany("PhieuMuon")
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuTras.ChiTietPhieuTra", b =>
                {
                    b.HasOne("Quanlythuvien.Models.Sachs.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quanlythuvien.Models.PhieuTras.PhieuTra", "PhieuTra")
                        .WithMany("ChiTietPhieuTras")
                        .HasForeignKey("PhieuTraMaPhieuTra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuTra");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuTras.PhieuTra", b =>
                {
                    b.HasOne("Quanlythuvien.Models.PhieuMuons.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuTras")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("Quanlythuvien.Models.DocGia", b =>
                {
                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuMuons.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("PhieuTras");
                });

            modelBuilder.Entity("Quanlythuvien.Models.PhieuTras.PhieuTra", b =>
                {
                    b.Navigation("ChiTietPhieuTras");
                });
#pragma warning restore 612, 618
        }
    }
}
